//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EDI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecureCoreG4Entities : DbContext
    {
        public SecureCoreG4Entities()
            : base("name=SecureCoreG4Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Agencies> Agencies { get; set; }
        public virtual DbSet<Factories> Factories { get; set; }
        public virtual DbSet<OperationalAreas> OperationalAreas { get; set; }
        public virtual DbSet<OrderInfo> OrderInfo { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<OrdersDetail> OrdersDetail { get; set; }
        public virtual DbSet<Planets> Planets { get; set; }
        public virtual DbSet<Priority> Priority { get; set; }
        public virtual DbSet<References> References { get; set; }
    }
}
