//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BBDD_Factories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factory
    {
        public short idFactory { get; set; }
        public string codeFactory { get; set; }
        public string DescFactory { get; set; }
    }
}
